// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 sol pbc

enum CertlessTrustFixtures {
    static let caPEM = """
    -----BEGIN CERTIFICATE-----
    MIIB7jCCAZSgAwIBAgIUVq2I/FNgYluciFdZ8KbXf0mjqTAwCgYIKoZIzj0EAwIw
    QzEiMCAGA1UEAwwZc29sc3RvbmUgY2VydGxlc3MgdGVzdCBDQTEQMA4GA1UECgwH
    c29sIHBiYzELMAkGA1UEBhMCVVMwHhcNMjYwNjE0MTcyOTMzWhcNMzYwNjExMTcy
    OTMzWjBDMSIwIAYDVQQDDBlzb2xzdG9uZSBjZXJ0bGVzcyB0ZXN0IENBMRAwDgYD
    VQQKDAdzb2wgcGJjMQswCQYDVQQGEwJVUzBZMBMGByqGSM49AgEGCCqGSM49AwEH
    A0IABN5fbgUSUO7Qe9dPHsE4gnEzUDoLwlxlN8xkMV3Pvz1hmnVCg9VjrI1QYZMn
    MfvcqSl/LroF1soNkgLRjpcHl8qjZjBkMB8GA1UdIwQYMBaAFFLJ3dC4g5zDGp1u
    Hv2zXqUKQtCbMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMB0G
    A1UdDgQWBBRSyd3QuIOcwxqdbh79s16lCkLQmzAKBggqhkjOPQQDAgNIADBFAiAq
    p2KuOvY+NX4n5+bFUVfnjzb1SlbpM0K0ncwFUSxZOwIhAP6IBDgWLwy0uJRP1bTE
    X5wsXrf8aV90TDMiWLJRpnHn
    -----END CERTIFICATE-----
    """

    static let leafPEM = """
    -----BEGIN CERTIFICATE-----
    MIICHTCCAcOgAwIBAgIUKjFGad5q5cb79R48WvVpqyDN3NUwCgYIKoZIzj0EAwIw
    QzEiMCAGA1UEAwwZc29sc3RvbmUgY2VydGxlc3MgdGVzdCBDQTEQMA4GA1UECgwH
    c29sIHBiYzELMAkGA1UEBhMCVVMwHhcNMjYwNjE0MTcyOTMzWhcNMzYwNjExMTcy
    OTMzWjBFMSQwIgYDVQQDDBtzb2xzdG9uZSBjZXJ0bGVzcyB0ZXN0IGxlYWYxEDAO
    BgNVBAoMB3NvbCBwYmMxCzAJBgNVBAYTAlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0D
    AQcDQgAE3E+aWwDtMT9KS7dpQ9Eq1P2k/nar+xBYrF3WQBCadtYAB+lXE+9pg8Gd
    9cxRNvdemtQmBaQNn9i8u+3Au/sx5qOBkjCBjzAMBgNVHRMBAf8EAjAAMA4GA1Ud
    DwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAdBgNVHQ4EFgQUur3Qm3Be
    KNZ+yurNAi2Nxvhz1+IwHwYDVR0jBBgwFoAUUsnd0LiDnMManW4e/bNepQpC0Jsw
    GgYDVR0RBBMwEYIJbG9jYWxob3N0hwR/AAABMAoGCCqGSM49BAMCA0gAMEUCIQCj
    tyh3VHHHaDG5yQKl20XtbfTYum+c/8cC/oSFpJz4uwIgIDVc+E2Pjs45I6FlFU5q
    x98VaTZiOEPB9DfuIMNctig=
    -----END CERTIFICATE-----
    """

    static let wrongCAPEM = """
    -----BEGIN CERTIFICATE-----
    MIIB8TCCAZagAwIBAgIUBLo9k/1dt74m/0q2pc2MI2AXikIwCgYIKoZIzj0EAwIw
    RDEjMCEGA1UEAwwac29sc3RvbmUgY2VydGxlc3Mgd3JvbmcgQ0ExEDAOBgNVBAoM
    B3NvbCBwYmMxCzAJBgNVBAYTAlVTMB4XDTI2MDYxNDE3MjkzM1oXDTM2MDYxMTE3
    MjkzM1owRDEjMCEGA1UEAwwac29sc3RvbmUgY2VydGxlc3Mgd3JvbmcgQ0ExEDAO
    BgNVBAoMB3NvbCBwYmMxCzAJBgNVBAYTAlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0D
    AQcDQgAELkUp055HKUEE30Knw1fIHL1/P+KK1Kz5YugchhhO1uevNCA5LjGeFNEP
    MyNB/t5KC57y0IorcP4m0v1c8RccEaNmMGQwHwYDVR0jBBgwFoAUxPB7zrgWE786
    CioSVHon/Y3lrZ0wEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAQYw
    HQYDVR0OBBYEFMTwe864FhO/OgoqElR6J/2N5a2dMAoGCCqGSM49BAMCA0kAMEYC
    IQCCvBqeCQKVtxJpaGNrhqajjRAB/lHiPxjt5WKsOk278wIhAKI6ha2yTdwQ3Jxh
    XFMS3tS+tPizhcMHI2EdTFFh58fQ
    -----END CERTIFICATE-----
    """

    static let chainPEM = "\(leafPEM)\n\(caPEM)\n"
    static let wrongChainPEM = "\(leafPEM)\n\(wrongCAPEM)\n"
}
